# Generated by python -m tools.generate_api. Do not edit by hand.
"""Typed player API. Gameplay implementation lives in game/objects/."""
from space_automation.types import CommandResult as CommandResult, Vector2 as Vector2
from .generated import Rover as Rover
from .generated import SolarPanel as SolarPanel
from .station import Station as Station, station as station
