# Generated by python -m tools.generate_api. Do not edit by hand.
from __future__ import annotations
from space_automation.types import CommandResult, Vector2
from .proxy import ObjectProxy


class Rover(ObjectProxy):
    'A surface vehicle controlled through one movement request per tick.'
    @property
    def position(self) -> Vector2:
        'Position in meters.'
        return self._read('position')

    @property
    def max_speed(self) -> float:
        'Maximum speed in meters per tick.'
        return self._read('max_speed')

    @property
    def max_energy(self) -> float:
        'Maximum energy stored.'
        return self._read('max_energy')

    @property
    def energy_recharging_speed(self) -> float:
        'Energy recharged per tick.'
        return self._read('energy_recharging_speed')

    @property
    def energy_consumption(self) -> float:
        'Energy consumed per tick when moving.'
        return self._read('energy_consumption')

    def move(self, direction: 'Vector2', speed: 'float') -> 'CommandResult':
        'Request movement for this tick. Direction is normalized; speed is capped.\n\nThe first valid request wins. Invalid requests do not consume the slot.'
        return self._call('move', direction, speed)



class SolarPanel(ObjectProxy):
    'Example producer. Accumulated energy is not yet connected to a grid.'
    @property
    def enabled(self) -> bool:
        'Whether the panel is producing energy.'
        return self._read('enabled')

    @property
    def energy_per_tick(self) -> float:
        'Energy produced per tick in joules.'
        return self._read('energy_per_tick')

    @property
    def energy_generated(self) -> float:
        'Total energy generated in joules.'
        return self._read('energy_generated')

    def set_enabled(self, enabled: 'bool') -> 'CommandResult':
        'Enable or disable generation. Multiple calls are allowed in a tick.'
        return self._call('set_enabled', enabled)



PROXY_TYPES = {
    'rover': Rover,
    'solar_panel': SolarPanel,
}
