"""Generate typed player wrappers from authoritative object definitions.

Run: python -m tools.generate_api
Check in CI: python -m tools.generate_api --check
"""
import argparse
import inspect
from pathlib import Path
from game.catalog import OBJECT_TYPES

TARGET = Path(__file__).resolve().parents[1] / 'expedition/generated.py'


def render(types):
    lines = ['# Generated by python -m tools.generate_api. Do not edit by hand.',
             'from __future__ import annotations',
             'from space_automation.types import CommandResult, Vector2',
             'from .proxy import ObjectProxy', '', '']
    for key, cls in types.items():
        lines += [f'class {cls.__name__}(ObjectProxy):', f'    {inspect.getdoc(cls)!r}']
        for item in cls.observations():
            if item.name == 'id':
                continue
            annotation = item.type if isinstance(item.type, str) else inspect.formatannotation(item.type)
            lines += ['    @property', f'    def {item.name}(self) -> {annotation}:',
                      f"        {item.metadata.get('doc', '')!r}", f'        return self._read({item.name!r})', '']
        for name, method in cls.commands().items():
            signature = inspect.signature(method)
            # Normal Python positional/keyword-only/default parameters are retained.
            arguments = []
            for parameter in list(signature.parameters.values())[1:]:
                if parameter.kind == parameter.VAR_POSITIONAL:
                    arguments.append('*' + parameter.name)
                elif parameter.kind == parameter.VAR_KEYWORD:
                    arguments.append('**' + parameter.name)
                elif parameter.kind == parameter.KEYWORD_ONLY:
                    arguments.append(parameter.name + '=' + parameter.name)
                else:
                    arguments.append(parameter.name)
            suffix = ', ' + ', '.join(arguments) if arguments else ''
            lines += [f'    def {name}{signature}:', f'        {inspect.getdoc(method)!r}',
                      f'        return self._call({name!r}{suffix})', '']
        lines += ['', '']
    lines += ['PROXY_TYPES = {']
    lines += [f'    {key!r}: {cls.__name__},' for key, cls in types.items()]
    lines += ['}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = render(OBJECT_TYPES)
    compile(source, str(TARGET), 'exec')
    exports = '\n'.join([
        '# Generated by python -m tools.generate_api. Do not edit by hand.',
        '"""Typed player API. Gameplay implementation lives in game/objects/."""',
        'from space_automation.types import CommandResult as CommandResult, Vector2 as Vector2',
        *[f'from .generated import {cls.__name__} as {cls.__name__}' for cls in OBJECT_TYPES.values()],
        'from .station import Station as Station, station as station', '',
    ])
    for path, content in ((TARGET, source), (TARGET.with_name('__init__.py'), exports)):
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, 'Player API is stale. Run python -m tools.generate_api.\n')
        else:
            path.write_text(content)
            print(f'Generated {path}')


if __name__ == '__main__':
    main()
